---
title: "Forecasting Discussion 1"
author: "Phil Jauregui"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
library(tidyverse)
library(fpp3)
library(tsibble)
library(tsibbledata)
library(lubridate)
library(stats)

d <- read.csv("C:/Users/jaure/Downloads/GlobalLandTemperatures_GlobalLandTemperaturesByState.csv", stringsAsFactors=TRUE)

d<-d|>filter(State == "California")
```

```{r}
filtered_data <- d %>%
  mutate(YearMonth = yearmonth(as.character(dt))) %>%
  as_tsibble(index = YearMonth) %>%
  filter(year(YearMonth) >= 1913 & year(YearMonth) <= 2013)

filtered_data %>%
  autoplot(AverageTemperature) +
  labs(y = "Average Temperature (Celsius)", x = NULL)
```

```{r}
plot <- filtered_data %>%
     ggplot(aes(x = YearMonth, y = AverageTemperature)) +
     geom_line() +
     geom_smooth(method = "lm", se = FALSE, color = "red") +
     labs(y = "Average Temperature (Celsius)", x = NULL)
 
print(plot)
```

```{r}
additivedecomposed <- filtered_data %>%
     select(YearMonth, AverageTemperature) %>%
     stl(t.window = 13, s.window = "periodic")
 
plot(additivedecomposed)
```

```{r}
multiplicativedecomposed <- filtered_data %>%
     select(YearMonth, AverageTemperature) %>%
     stl(t.window = 13, s.window = "periodic", robust = TRUE)
 
plot(multiplicativedecomposed)
```